### ISSUE TITLE
README内の文面とLicenseが一致していない

### ISSUE THREAD

**Issue by mkaraki** [siraisi368/KyoshinMonitor-EEW-Observer-REV-2#2]
README.md内の[この文](https://github.com/siraisi368/KyoshinMonitor-EEW-Observer-REV-2/blob/master/README.md?plain=1#L5)は、指定されている[Apache-2.0 License](https://github.com/siraisi368/KyoshinMonitor-EEW-Observer-REV-2/blob/master/LICENSE)のものと矛盾しています。

**Comment by siraisi368** [comment]
ご指摘ありがとうございます。
README.md内の対応する文章の書き換えで対応させていただきます。
